### ISSUE TITLE
Docker Image does not work after update

### ISSUE THREAD

**Issue by AlexMAS** [yandex/ClickHouse#1464]
Hello!

A month ago or a little bit more I used ClickHouse with Docker and it worked fine. Recently I updated my Docker to the latest version and returned to my project. When I've tried to start ClickHouse as before I saw errors. I've tried to use previous versions of ClickHouse but it didn't help.

Currently I try to run ClickHouse image and mount the container data directory to the specified host directory. Something like that:

```bash
$ docker run -it --rm -v C:\tmp\data:/var/lib/clickhouse -p 9000:9000 -p 8123:8123 -p 9009:9009 --ulimit nofile=262144:262144 yandex/clickhouse-server
```

And I always see the same output:

```bash
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
2017.11.08 05:02:52.667288 [ 1 ] <Warning> Application: Logging to console
2017.11.08 05:02:52.670953 [ 1 ] <Information> : Starting daemon with revision 54310
2017.11.08 05:02:52.671099 [ 1 ] <Information> Application: starting up
2017.11.08 05:02:52.671827 [ 1 ] <Error> Application: Access to file denied: /var/lib/clickhouse/data
2017.11.08 05:02:52.671849 [ 1 ] <Information> Application: shutting down
2017.11.08 05:02:52.671854 [ 1 ] <Debug> Application: Uninitializing subsystem: Logging Subsystem
2017.11.08 05:02:52.671956 [ 2 ] <Information> BaseDaemon: Stop SignalListener thread
```

I've found the related issue but it doesn't have an appropriate solution: https://stackoverflow.com/questions/46917533/data-directory-permissions-on-host-for-clickhouse-installation-via-docker

OS:
```bash
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.15063 N/A Build 15063
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
```

Docker:
```bash
$ docker -v
Docker version 17.09.0-ce, build afdb6d4
```

**Comment by AlexMAS** [comment]
On Linux the same behaviour. Can anyone help me? May be I need run the container with some privileges?

**Comment by tacyuuhon** [comment]
I also had the same problem. And SELinux is disabled.
But it does work fine on macOS[10.13.1 (17B48)]

Linux

```
$ lsb_release  #-a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core) 
Release:        7.3.1611
Codename:       Core
```

Docker
```
$ docker -v
Docker version 17.06.2-ce, build cec0b72
```

Docker-Compose
```
$ docker-compose  -v
docker-compose version 1.17.0, build ac53b73
```

docker-compose.yml
```
version: '3'
services:
    clickhouse-server: 
      image: yandex/clickhouse-server:1.1.54310
      restart: always
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      network_mode: host
      ports:
        - 8123:8123
        - 9000:9000
        - 9009:9009
      volumes:
        - ./data/clickhouse:/var/lib/clickhouse
        - ./conf/clickhouse/config.xml:/etc/clickhouse-server/config.xml
        - ./conf/clickhouse/users.xml:/etc/clickhouse-server/users.xml
```
