### ISSUE TITLE
"Expected end of line." exception when reading CSV data from Kafka stream

### ISSUE THREAD

**Issue by marklit** [yandex/ClickHouse#2298]
I'm using Kafka 1.1.0 and ClickHouse 1.1.54380.

When I try to select CSV data from a Kafka topic using ClickHouse I get a complaint of "Expected end of line.". These are the steps needed to re-produce the issue:

```bash
$ /opt/kafka/bin/kafka-topics.sh \
    --create \
    --zookeeper localhost:2181 \
    --replication-factor 1 \
    --partitions 1 \
    --topic weather2

$ clickhouse-client
```

```sql
CREATE TABLE weather_queue2 (
        date String,
        actual_mean_temp String,
        actual_min_temp String,
        actual_max_temp String,
        average_min_temp String,
        average_max_temp String,
        record_min_temp String,
        record_max_temp String,
        record_min_temp_year String,
        record_max_temp_year String,
        actual_precipitation String,
        average_precipitation String,
        record_precipitation String
    ) ENGINE = Kafka('localhost:9092', 'weather2', 'group1', 'CSV');
```

```bash
$ vi weather.csv
```

```
2014-7-1,81,70,91,67,89,56,104,1919,2012,0.00,0.10,5.91
2014-7-2,85,74,95,68,89,56,101,2008,1931,0.00,0.10,1.53
2014-7-3,82,71,93,68,89,56,99,2010,1931,0.14,0.11,2.50
2014-7-4,75,64,86,68,89,55,99,1933,1955,0.00,0.10,2.63
2014-7-5,72,60,84,68,89,57,100,1967,1954,0.00,0.10,1.65
2014-7-6,74,61,87,68,89,57,99,1964,1948,0.00,0.10,1.95
2014-7-7,79,67,91,68,89,55,100,1972,1954,0.00,0.11,2.37
2014-7-8,83,72,94,68,89,58,101,1892,2010,0.00,0.11,1.87
2014-7-9,80,71,89,68,89,57,101,1891,1986,0.15,0.12,3.71
2014-7-10,78,71,85,68,89,53,101,1961,1926,0.0,0.11,2.45
```

```bash
$ cat weather.csv \
    | /opt/kafka/bin/kafka-console-producer.sh \
        --topic weather2 \
        --broker-list localhost:9092

$ /opt/kafka/bin/kafka-console-consumer.sh \
    --topic weather2 \
    --zookeeper 127.0.0.1:2181 \
    --from-beginning \
    | head -n5
```

```
2014-7-1,81,70,91,67,89,56,104,1919,2012,0.00,0.10,5.91
2014-7-2,85,74,95,68,89,56,101,2008,1931,0.00,0.10,1.53
2014-7-3,82,71,93,68,89,56,99,2010,1931,0.14,0.11,2.50
2014-7-4,75,64,86,68,89,55,99,1933,1955,0.00,0.10,2.63
2014-7-5,72,60,84,68,89,57,100,1967,1954,0.00,0.10,1.65
```

```bash
$ clickhouse-client
```

```sql
SELECT * FROM weather_queue2;
```

```
SELECT *
FROM weather_queue2

Received exception from server (version 1.1.54380):
Code: 117. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Expected end of line.

0 rows in set. Elapsed: 0.058 sec.
```

**Comment by marklit** [comment]
For reference I adjusted the CSV content to the following and I'm still seeing the same exception from ClickHouse.

```
"2014-07-01","81","70","91","67","89","56","104","1919","2012","0.00","0.10","5.91"
"2014-07-02","85","74","95","68","89","56","101","2008","1931","0.00","0.10","1.53"
"2014-07-03","82","71","93","68","89","56","99","2010","1931","0.14","0.11","2.50"
"2014-07-04","75","64","86","68","89","55","99","1933","1955","0.00","0.10","2.63"
"2014-07-05","72","60","84","68","89","57","100","1967","1954","0.00","0.10","1.65"
"2014-07-06","74","61","87","68","89","57","99","1964","1948","0.00","0.10","1.95"
"2014-07-07","79","67","91","68","89","55","100","1972","1954","0.00","0.11","2.37"
"2014-07-08","83","72","94","68","89","58","101","1892","2010","0.00","0.11","1.87"
"2014-07-09","80","71","89","68","89","57","101","1891","1986","0.15","0.12","3.71"
"2014-07-10","78","71","85","68","89","53","101","1961","1926","0.0","0.11","2.45"
```

**Comment by marklit** [comment]
@LiuYangkuan any ETA on when your changes will be merged into master and released?

**Comment by alexey-milovidov** [comment]
Fixed by #2701

**Comment by 4n70w4** [comment]
@alexey-milovidov 

I have the same problem on the same data.

```
SELECT *
FROM weather_queue2

Received exception from server (version 18.14.13):
Code: 117. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Expected end of line: (at row 1)
Could not print diagnostic info because two last rows aren't in buffer (rare case)
.

0 rows in set. Elapsed: 0.002 sec.
```

docker-compose.yml

```
version: '3'

services:

  clickhouse:
    hostname: clickhouse
    image: yandex/clickhouse-server


  kafka:
    depends_on:
      - zookeeper
    hostname: kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    hostname: zookeeper
    image: zookeeper
```
