### ISSUE TITLE
Too many open files while using materialized view with kafka source

### ISSUE THREAD

**Issue by AlexRinn** [yandex/ClickHouse#3198]
Greetings. 
I have Ubuntu 18.04 source system. Clickhouse server version - 18.12.17. Default config.
Database structure creation:
```
create table a (EventDate Date) ENGINE MergeTree() partition by toYYYYMM(EventDate) order by (EventDate) settings index_granularity=8192;

create table k (EventDate Date) ENGINE=Kafka SETTINGS
  kafka_broker_list = 'localhost:9092,localhost:9093,localhost:9094',
  kafka_topic_list = 'a',
  kafka_group_name = 'group1',
  kafka_format = 'JSONEachRow';

create materialized view w to a as select * from k;
```
As soon, as materialized view was created, amount of file descriptors for clickhouse server process starts to grow each second to the limit of max open files. 
Error logs are empty. Usual log contains only debug ant trace info. However syslog contains following errors:
```
Sep 22 18:22:38 kernel: [25449.716131] netlink: 'TCPHandler': attribute type 1 has an invalid length.
Sep 22 18:22:38 kernel: [25449.729949] netlink: 'TCPHandler': attribute type 1 has an invalid length.
Sep 22 18:22:40 kernel: [25451.228134] netlink: 'ParalInputsProc': attribute type 1 has an invalid length.
Sep 22 18:22:40 kernel: [25451.228175] netlink: 'ParalInputsProc': attribute type 1 has an invalid length.
Sep 22 18:22:42 kernel: [25453.227433] netlink: 'ParalInputsProc': attribute type 1 has an invalid length.
```
Am I missing something? Any help would be much appreciated.

**Comment by kmatt** [comment]
Does setting `kafka_num_consumers = 1` in the Kafka table stop the errors?

https://clickhouse.yandex/docs/en/operations/table_engines/kafka/

**Comment by AlexRinn** [comment]
Thank you for response. Changed kafka table creation to:
`CREATE TABLE default.k ( EventDate Date) ENGINE = Kafka SETTINGS kafka_broker_list = 'localhost:9092,localhost:9093,localhost:9094', kafka_topic_list = 'a', kafka_group_name = 'group1', kafka_format = 'JSONEachRow', kafka_num_consumers = 1`
Unfortunately, problem is still present.

**Comment by snorecone** [comment]
We are also seeing this issue. Clickhouse currently has 456,357 files open; they are mostly netlink sockets:

```
clickhous 5174 clickhouse *377u     sock                0,8       0t0 41551004 protocol: NETLINK
clickhous 5174 clickhouse *378u     sock                0,8       0t0 41551005 protocol: NETLINK
clickhous 5174 clickhouse *395u     sock                0,8       0t0 41551817 protocol: NETLINK
clickhous 5174 clickhouse *396u     sock                0,8       0t0 41551818 protocol: NETLINK
```

At this point the kafka table engine + MV is unusable. Our clickhouse version is `18.12.13 revision 54407`. I'm happy to provide more info to help debug the problem.

**Comment by arstd** [comment]
We meet this problem too. So sad!

**Comment by filimonov** [comment]
1) Do you use clickhouse from packages, or build from sources? 
2) can you also check clickhouse-server.log (not an err.log) for something suspicious?
3) how many nodes do you have in your kafka cluster.
4) can you try to consume messages with kafkacat from the same host where CH is installed?

**Comment by AlexRinn** [comment]
1. Kafkacat and native consume\produce scripts of kafka dist work normally with local kafka.
2. Clickhouse was installed from package
3. Nothing suspicious in either log.
4. 3 nodes of kafka.


Kafka is running via following docker-compose: 
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: "2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka3:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
   Clickhouse server is running on system outside of created docker network. If clickhouse is added as new service to docker-compose - all works fine. So as workaround for now we moved production implementation to separate docker container.
