### ISSUE TITLE
Last Docker image seems broken

### ISSUE THREAD

**Issue by R242** [yandex/ClickHouse#3374]
I started the last Docker image and I got the error:

`Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = File not found: ${CLICKHOUSE_CONFIG}, e.what() = File not found`

Clickhouse is started by:
`CMD ["/usr/bin/clickhouse-server", "--config=${CLICKHOUSE_CONFIG}"]`
But CMD doesn't support variables.

**Comment by frankie4fingers** [comment]
It seems it broken starts from 18.14.* I checked today several published versions and only 18.12.17 works fine for me. All shows the same error reported above.

**Comment by bartkappenburg** [comment]
If you use ClickHouse with docker compose you can fix this by adding the correct upstart command. Here's my docker-compose.yml:

```
clickhouse:
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 362144
    image: yandex/clickhouse-server
    logging:
      driver: json-file
    volumes:
      - /dev/shm:/dev/shm
      - ./config.xml:/etc/clickhouse-server/config.xml
    ports:
      - "8123:8123"
      - "9000:9000"
    command: /usr/bin/clickhouse-server --config=/etc/clickhouse-server/config.xml
```
