### ISSUE TITLE
Again «expected end of line» exception when reading CSV/TSV data from Kafka stream

### ISSUE THREAD

**Issue by 4n70w4** [yandex/ClickHouse#3579]
See source data, commands, tables and queries here: https://github.com/yandex/ClickHouse/issues/2298

```
SELECT *
FROM weather_queue2

Received exception from server (version 18.14.13):
Code: 117. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Expected end of line: (at row 1)
Could not print diagnostic info because two last rows aren't in buffer (rare case)
.

0 rows in set. Elapsed: 0.002 sec.
```

docker-compose.yml

```
version: '3'

services:

  clickhouse:
    hostname: clickhouse
    image: yandex/clickhouse-server


  kafka:
    depends_on:
      - zookeeper
    hostname: kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    hostname: zookeeper
    image: zookeeper
```
